In [61]:
#Import Required Libraries
import pandas as pd
import numpy as np

In [62]:
#Load the Datasets
country = pd.read_csv("country_metadata.csv")
trade = pd.read_csv("trade_routes.csv")
timeline = pd.read_csv("weekly_timeline.csv")
commodity = pd.read_csv("commodity_market.csv")
geo = pd.read_csv("geopolitical_events.csv")
operations = pd.read_csv("weekly_route_operations.csv")

In [63]:
#Initial Data Inspection
country.head()

,country,iso3,region,income_group,population,gdp_per_capita,trade_dependency_score,port_capacity_index,logistics_performance_index
0,China,CHN,East Asia & Pacific,Upper middle income,670991378,1769,51.99,74.42,68.80
1,India,IND,South Asia,High income,430389014,60735,23.73,56.04,86.66
2,United States,USA,North America,Low income,250467210,63955,97.90,21.06,33.87
3,Germany,DEU,Europe & Central Asia,Upper middle income,1434267572,65925,38.62,95.38,51.28
4,Japan,JPN,East Asia & Pacific,Upper middle income,435285667,68969,27.25,65.06,34.58

In [5]:
country.shape

(10, 9)

In [6]:
country.columns

Index(['country', 'iso3', 'region', 'income_group', 'population',
       'gdp_per_capita', 'trade_dependency_score', 'port_capacity_index',
       'logistics_performance_index'],
      dtype='object')

In [7]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country                      10 non-null     object
 1   iso3                         10 non-null     object
 2   region                       10 non-null     object
 3   income_group                 10 non-null     object
 4   population                   10 non-null     int64
 5   gdp_per_capita               10 non-null     int64
 6   trade_dependency_score       10 non-null     float64
 7   port_capacity_index          10 non-null     float64
 8   logistics_performance_index  10 non-null     float64
dtypes: float64(3), int64(2), object(4)
memory usage: 852.0+ bytes

In [8]:
country.describe()

,population,gdp_per_capita,trade_dependency_score,port_capacity_index,logistics_performance_index
count,1.000000e+01,10.000000,10.000000,10.000000,10.000000
mean,5.712431e+08,45165.400000,60.436000,53.648000,53.420000
std,3.870457e+08,26728.867109,27.594285,24.278277,21.587173
min,8.940975e+07,1769.000000,23.730000,21.060000,22.510000
25%,2.954477e+08,27416.750000,41.615000,38.672500,35.095000
50%,5.249470e+08,57721.000000,54.665000,53.435000,52.645000
75%,6.655088e+08,65432.500000,83.967500,72.080000,67.955000
max,1.434268e+09,72932.000000,98.660000,95.380000,86.660000

In [9]:
country.duplicated().sum()

0

In [10]:
country.shape

(10, 9)

In [64]:
# Validate Primary Key

# A valid primary key should:
# 1. Contain no missing values.
# 2. Contain unique values.

if country["iso3"].nunique() == len(country):
    print("'iso3' is a valid Primary Key.")
else:
    print("'iso3' is NOT a valid Primary Key.")

'iso3' is a valid Primary Key.

In [65]:
# Check if any country has an invalid population (<= 0)

(country["population"] <= 0).sum()

0

In [66]:
# Check if GDP per capita contains invalid values (<= 0)

(country["gdp_per_capita"] <= 0).sum()

0

In [67]:
# Check if trade dependency score is outside the valid range (0-100)

country[
    (country["trade_dependency_score"] < 0) |
    (country["trade_dependency_score"] > 100)
]

Empty DataFrame
Columns: [country, iso3, region, income_group, population, gdp_per_capita, trade_dependency_score, port_capacity_index, logistics_performance_index]
Index: []

In [68]:
# Check if port capacity index is outside the valid range (0-100)

country[
    (country["port_capacity_index"] < 0) |
    (country["port_capacity_index"] > 100)
]

Empty DataFrame
Columns: [country, iso3, region, income_group, population, gdp_per_capita, trade_dependency_score, port_capacity_index, logistics_performance_index]
Index: []

In [69]:
# Check if logistics performance index is outside the valid range (0-100)

country[
    (country["logistics_performance_index"] < 0) |
    (country["logistics_performance_index"] > 100)
]

Empty DataFrame
Columns: [country, iso3, region, income_group, population, gdp_per_capita, trade_dependency_score, port_capacity_index, logistics_performance_index]
Index: []

# Conclusion

- No missing values found.
- No duplicate rows found.
- Data types are correct.
- The primary key is valid.
- No invalid values were detected.

## Result

The dataset is clean and ready for analysis.

In [70]:
# Display the first five rows
trade.head()

,route_id,origin_country,destination_country,distance_km,shipping_method,trade_route_type,estimated_transit_days
0,R00001,India,United States,8746,Rail,Consumer Goods,19
1,R00002,Japan,China,5420,Air,Agriculture,29
2,R00003,Australia,China,12247,Rail,Consumer Goods,16
3,R00004,Australia,Canada,12143,Road,Energy,32
4,R00005,United Kingdom,United States,14048,Sea,Energy,37

In [13]:
# Check dataset dimensions
trade.shape

(50, 7)

In [14]:
# View column names
trade.columns

Index(['route_id', 'origin_country', 'destination_country', 'distance_km',
       'shipping_method', 'trade_route_type', 'estimated_transit_days'],
      dtype='object')

In [71]:
# Check data types and missing values
trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                50 non-null     object
 1   origin_country          50 non-null     object
 2   destination_country     50 non-null     object
 3   distance_km             50 non-null     int64
 4   shipping_method         50 non-null     object
 5   trade_route_type        50 non-null     object
 6   estimated_transit_days  50 non-null     int64
dtypes: int64(2), object(5)
memory usage: 2.9+ KB

In [17]:
# Display summary statistics
trade.describe()

        distance_km  estimated_transit_days
count     50.000000               50.000000
mean    7333.600000               25.120000
std     3865.000795               12.266829
min      564.000000                3.000000
25%     4921.500000               16.000000
50%     7652.500000               26.500000
75%    10278.500000               35.500000
max    14048.000000               45.000000

In [5]:
# Check missing values
trade.isnull().sum()

route_id                  0
origin_country            0
destination_country       0
distance_km               0
shipping_method           0
trade_route_type          0
estimated_transit_days    0
dtype: int64

In [18]:
# Check duplicate rows
trade.duplicated().sum()

0

In [6]:
# Validate the primary key

if trade["route_id"].nunique() == len(trade):
    print("'route_id' is a valid Primary Key.")
else:
    print("'route_id' is NOT a valid Primary Key.")

'route_id' is a valid Primary Key.

In [19]:
# Check if route distance contains invalid values (<= 0)

(trade["distance_km"] <= 0).sum()

0

In [20]:
# Check if estimated transit days contain invalid values (<= 0)

(trade["estimated_transit_days"] <= 0).sum()

0

In [21]:
# Check if origin and destination countries are the same

trade[trade["origin_country"] == trade["destination_country"]]

Empty DataFrame
Columns: [route_id, origin_country, destination_country, distance_km, shipping_method, trade_route_type, estimated_transit_days]
Index: []

In [22]:
# View unique shipping methods

trade["shipping_method"].unique()

array(['Rail', 'Air', 'Road', 'Sea'], dtype=object)

## Conclusion

- No missing values found.
- No duplicate rows found.
- Data types are correct.
- Primary key (`route_id`) is valid.
- Route distance contains no invalid values.
- Estimated transit days contain no invalid values.
-  Origin and destination countries are valid.

### Result

The `trade_routes.csv` dataset is clean and ready for analysis.

In [14]:
timeline.head()

        date
0 2015-01-04
1 2015-01-11
2 2015-01-18
3 2015-01-25
4 2015-02-01

In [72]:
timeline.shape

(626, 1)

In [73]:
timeline.columns

Index(['date'], dtype='object')

In [74]:
timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    626 non-null    object
dtypes: object(1)
memory usage: 5.0+ KB

In [75]:
timeline.describe()

              date
count          626
unique         626
top     2015-01-04
freq             1

In [76]:
timeline.duplicated().sum()

0

In [77]:
# Convert the date column to datetime

timeline["date"] = pd.to_datetime(timeline["date"])

In [78]:
# Verify the updated data type

timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    626 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 5.0 KB

In [79]:
# Validate the primary key

if timeline["date"].nunique() == len(timeline):
    print("'date' is a valid Primary Key.")
else:
    print("'date' is NOT a valid Primary Key.")

'date' is a valid Primary Key.

In [80]:
# Check whether all dates are between 2015 and 2026

timeline[
    (timeline["date"].dt.year < 2015) |
    (timeline["date"].dt.year > 2026)
]

Empty DataFrame
Columns: [date]
Index: []

In [81]:
# Check for duplicate dates

timeline["date"].duplicated().sum()

0

## Conclusion

- No missing values found.
- No duplicate rows found.
- Data type converted to datetime.
- Primary key (`date`) is valid.
- All dates fall within the expected period (2015 to 2026).

### Result

The `weekly_timeline.csv` dataset is clean and ready for analysis.

In [82]:
commodity.head()

,date,oil_price,natural_gas_price,steel_price,wheat_price,copper_price,commodity_stress_index
0,2015-01-04,62.483571,2.505198,500.313218,186.331236,6674.454842,19.20
1,2015-01-11,59.308678,2.937107,618.702828,203.882599,6752.376841,35.05
2,2015-01-18,63.238443,3.027862,661.383450,239.297033,7884.728328,74.22
3,2015-01-25,67.615149,3.547096,539.517949,252.311656,7373.403874,68.59
4,2015-02-01,58.829233,2.153768,683.628619,195.313023,6594.677690,28.98

In [28]:
commodity.shape

(626, 7)

In [29]:
commodity.columns

Index(['date', 'oil_price', 'natural_gas_price', 'steel_price', 'wheat_price',
       'copper_price', 'commodity_stress_index'],
      dtype='object')

In [83]:
commodity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    626 non-null    object
 1   oil_price               626 non-null    float64
 2   natural_gas_price       626 non-null    float64
 3   steel_price             626 non-null    float64
 4   wheat_price             626 non-null    float64
 5   copper_price            626 non-null    float64
 6   commodity_stress_index  626 non-null    float64
dtypes: float64(6), object(1)
memory usage: 34.4+ KB

In [31]:
commodity.describe()

,oil_price,natural_gas_price,steel_price,wheat_price,copper_price,commodity_stress_index
count,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000
mean,63.283259,3.367522,620.488475,230.935178,7045.812727,50.660268
std,13.542967,1.232910,69.132703,41.016023,337.852526,17.190195
min,30.655564,1.551872,453.932476,159.609757,6102.659209,10.480000
25%,56.411705,2.695510,574.066257,209.015206,6823.515119,38.652500
50%,61.070184,3.062777,610.043221,222.951465,7039.586135,49.090000
75%,65.717606,3.523899,656.122691,236.593360,7245.638785,60.082500
max,115.566016,8.956497,911.847728,407.644789,8341.383243,96.740000

In [26]:
# Check missing values
commodity.isnull().sum()

date                      0
oil_price                 0
natural_gas_price         0
steel_price               0
wheat_price               0
copper_price              0
commodity_stress_index    0
dtype: int64

In [35]:
commodity.duplicated().sum()

0

In [84]:
# Convert the date column to datetime

commodity["date"] = pd.to_datetime(commodity["date"])

In [85]:
# Verify the updated data types

commodity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    626 non-null    datetime64[ns]
 1   oil_price               626 non-null    float64
 2   natural_gas_price       626 non-null    float64
 3   steel_price             626 non-null    float64
 4   wheat_price             626 non-null    float64
 5   copper_price            626 non-null    float64
 6   commodity_stress_index  626 non-null    float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 34.4 KB

In [29]:
# Validate the primary key

if commodity["date"].nunique() == len(commodity):
    print("'date' is a valid Primary Key.")
else:
    print("'date' is NOT a valid Primary Key.")

'date' is a valid Primary Key.

In [30]:
# Check if commodity prices contain invalid values (<= 0)

price_columns = [
    "oil_price",
    "natural_gas_price",
    "steel_price",
    "wheat_price",
    "copper_price"
]

(commodity[price_columns] <= 0).sum()

oil_price            0
natural_gas_price    0
steel_price          0
wheat_price          0
copper_price         0
dtype: int64

In [31]:
# Check if commodity stress index is outside the valid range (0-100)

commodity[
    (commodity["commodity_stress_index"] < 0) |
    (commodity["commodity_stress_index"] > 100)
]

Empty DataFrame
Columns: [date, oil_price, natural_gas_price, steel_price, wheat_price, copper_price, commodity_stress_index]
Index: []

## Conclusion

- No missing values found.
- No duplicate rows found.
- Date column converted to datetime.
- Primary key (`date`) is valid.
- All commodity prices are valid.
- Commodity stress index values are valid.

### Result

The `commodity_market.csv` dataset is clean and ready for analysis.

In [86]:
geo.head()

,event_id,date,event_type,severity,affected_region,duration_days,risk_increase
0,E000001,2017-05-10 00:00:00,Cyber Attack,8,Europe,195,20.99
1,E000002,2024-06-06 00:00:00,Port Strike,4,South America,158,8.90
2,E000003,2021-07-19 00:00:00,Cyber Attack,6,Asia,198,19.30
3,E000004,2026-04-10 00:00:00,Diplomatic Crisis,9,Africa,55,53.06
4,E000005,2019-12-12 00:00:00,Political Unrest,3,Asia,61,6.56

In [87]:
geo.shape

(10003, 7)

In [88]:
geo.columns

Index(['event_id', 'date', 'event_type', 'severity', 'affected_region',
       'duration_days', 'risk_increase'],
      dtype='object')

In [39]:
geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10003 entries, 0 to 10002
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         10003 non-null  object
 1   date             10003 non-null  object
 2   event_type       10003 non-null  object
 3   severity         10003 non-null  int64
 4   affected_region  10003 non-null  object
 5   duration_days    10003 non-null  int64
 6   risk_increase    10003 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 547.2+ KB

In [40]:
geo.describe()

           severity  duration_days  risk_increase
count  10003.000000   10003.000000   10003.000000
mean       5.517345     186.382685      21.975127
std        2.867077     104.028748      13.347118
min        1.000000       7.000000       2.010000
25%        3.000000      96.000000      11.060000
50%        6.000000     186.000000      20.230000
75%        8.000000     277.000000      30.990000
max       10.000000    1000.000000      60.000000

In [41]:
geo.duplicated().sum()

0

In [89]:
# Convert mixed date formats to datetime

geo["date"] = pd.to_datetime(geo["date"], format="mixed")

In [90]:
geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10003 entries, 0 to 10002
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         10003 non-null  object
 1   date             10003 non-null  datetime64[ns]
 2   event_type       10003 non-null  object
 3   severity         10003 non-null  int64
 4   affected_region  10003 non-null  object
 5   duration_days    10003 non-null  int64
 6   risk_increase    10003 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 547.2+ KB

In [91]:
# Check for invalid dates

geo["date"].isnull().sum()

0

In [37]:
# Validate the primary key

if geo["event_id"].nunique() == len(geo):
    print("'event_id' is a valid Primary Key.")
else:
    print("'event_id' is NOT a valid Primary Key.")

'event_id' is a valid Primary Key.

In [38]:
# Check if severity is outside the valid range (1-10)

geo[
    (geo["severity"] < 1) |
    (geo["severity"] > 10)
]

Empty DataFrame
Columns: [event_id, date, event_type, severity, affected_region, duration_days, risk_increase]
Index: []

In [39]:
# Check if duration contains invalid values (<= 0)

(geo["duration_days"] <= 0).sum()

0

In [40]:
# Check if risk increase is outside the valid range (0-100)

geo[
    (geo["risk_increase"] < 0) |
    (geo["risk_increase"] > 100)
]

Empty DataFrame
Columns: [event_id, date, event_type, severity, affected_region, duration_days, risk_increase]
Index: []

In [41]:
# Check if dates are within the project period (2015-2026)

geo[
    (geo["date"].dt.year < 2015) |
    (geo["date"].dt.year > 2026)
]

Empty DataFrame
Columns: [event_id, date, event_type, severity, affected_region, duration_days, risk_increase]
Index: []

## Conclusion

- No missing values found.
- No duplicate rows found.
- Date column converted to datetime.
- Mixed date formats were identified and successfully converted.
- Primary key (`event_id`) is valid.
- Severity values are valid.
- Duration values are valid.
- Risk increase values are valid.
- Event dates are within the expected period (2015-2026).

### Result

The `geopolitical_events.csv` dataset is clean and ready for analysis.

In [92]:
operations.head()

,date,route_id,trade_volume_tonnes,shipping_delay_days,freight_cost_usd,container_availability_index,port_congestion_index,fuel_cost_index,commodity_price_index,weather_disruption_score,geopolitical_risk_score,route_status,carbon_emissions_tonnes
0,2015-01-04,R00001,8418.69,7.55,4586.66,71.42,82.22,62.48,19.20,59.51,57.15,Delayed,3681.49
1,2015-01-11,R00001,9343.00,9.33,4574.70,79.27,72.01,59.31,35.05,91.27,41.47,Delayed,4085.69
2,2015-01-18,R00001,7090.69,3.67,4520.46,60.16,44.64,63.24,74.22,46.69,79.69,Normal,3100.76
3,2015-01-25,R00001,7829.79,9.22,4696.95,66.43,97.82,67.62,68.59,56.39,67.15,Delayed,3423.97
4,2015-02-01,R00001,11339.59,6.36,4507.98,96.20,73.21,58.83,28.98,95.92,7.59,Delayed,4958.80

In [93]:
operations.shape

(31300, 13)

In [94]:
operations.columns

Index(['date', 'route_id', 'trade_volume_tonnes', 'shipping_delay_days',
       'freight_cost_usd', 'container_availability_index',
       'port_congestion_index', 'fuel_cost_index', 'commodity_price_index',
       'weather_disruption_score', 'geopolitical_risk_score', 'route_status',
       'carbon_emissions_tonnes'],
      dtype='object')

In [95]:
operations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31300 entries, 0 to 31299
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          31300 non-null  object
 1   route_id                      31300 non-null  object
 2   trade_volume_tonnes           31300 non-null  float64
 3   shipping_delay_days           31300 non-null  float64
 4   freight_cost_usd              31300 non-null  float64
 5   container_availability_index  31300 non-null  float64
 6   port_congestion_index         31300 non-null  float64
 7   fuel_cost_index               31300 non-null  float64
 8   commodity_price_index         31300 non-null  float64
 9   weather_disruption_score      31300 non-null  float64
 10  geopolitical_risk_score       31300 non-null  float64
 11  route_status                  31300 non-null  object
 12  carbon_emissions_tonnes       31300 non-null  float64
dtypes: float64(10), object(3)
memory usage: 3.1+ MB

In [47]:
operations.describe()

,trade_volume_tonnes,shipping_delay_days,freight_cost_usd,container_availability_index,port_congestion_index,fuel_cost_index,commodity_price_index,weather_disruption_score,geopolitical_risk_score,carbon_emissions_tonnes
count,31300.000000,31300.000000,31300.000000,31300.000000,31300.000000,31300.000000,31300.000000,31300.000000,31300.000000,31300.000000
mean,18823.910606,6.381002,4058.009023,75.050266,49.697852,61.516981,50.079984,50.560283,50.957961,6454.535299
std,9693.552809,2.963550,1611.577578,14.448535,28.812003,10.929600,16.874809,28.791971,29.086102,4699.908491
min,2372.895000,0.000000,685.430000,50.010000,0.000000,30.660000,10.480000,0.000000,0.000000,213.030000
25%,11609.895000,4.330000,2950.445000,62.540000,24.780000,56.080000,38.180000,25.747500,25.950000,2983.857500
50%,17108.200000,6.320000,4215.945000,75.180000,49.380000,60.710000,48.820000,50.855000,50.970000,5718.980000
75%,24730.025000,8.380000,5217.350000,87.690000,74.802500,64.770000,59.230000,75.500000,76.232500,8857.477500
max,49380.230000,20.952000,9659.594000,100.000000,100.000000,102.880000,96.740000,99.990000,100.000000,33095.970000

In [48]:
operations.duplicated().sum()

0

In [96]:
operations.isnull().sum()

date                            0
route_id                        0
trade_volume_tonnes             0
shipping_delay_days             0
freight_cost_usd                0
container_availability_index    0
port_congestion_index           0
fuel_cost_index                 0
commodity_price_index           0
weather_disruption_score        0
geopolitical_risk_score         0
route_status                    0
carbon_emissions_tonnes         0
dtype: int64

In [44]:
# Validate the composite primary key

if operations.duplicated(subset=["date", "route_id"]).sum() == 0:
    print("('date', 'route_id') is a valid Composite Primary Key.")
else:
    print("Duplicate records found.")

('date', 'route_id') is a valid Composite Primary Key.

In [97]:
# Convert the date column to datetime

operations["date"] = pd.to_datetime(
    operations["date"],
    format="mixed"
)

In [98]:
operations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31300 entries, 0 to 31299
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          31300 non-null  datetime64[ns]
 1   route_id                      31300 non-null  object
 2   trade_volume_tonnes           31300 non-null  float64
 3   shipping_delay_days           31300 non-null  float64
 4   freight_cost_usd              31300 non-null  float64
 5   container_availability_index  31300 non-null  float64
 6   port_congestion_index         31300 non-null  float64
 7   fuel_cost_index               31300 non-null  float64
 8   commodity_price_index         31300 non-null  float64
 9   weather_disruption_score      31300 non-null  float64
 10  geopolitical_risk_score       31300 non-null  float64
 11  route_status                  31300 non-null  object
 12  carbon_emissions_tonnes       31300 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(2)
memory usage: 3.1+ MB

In [47]:
# Check numeric columns that should contain positive values

positive_columns = [
    "trade_volume_tonnes",
    "freight_cost_usd",
    "carbon_emissions_tonnes"
]

(operations[positive_columns] <= 0).sum()

trade_volume_tonnes        0
freight_cost_usd           0
carbon_emissions_tonnes    0
dtype: int64

In [50]:
# Check if fuel cost contains invalid values (<= 0)

(operations["fuel_cost_index"] <= 0).sum()

0

In [51]:
# Check shipping delay values

(operations["shipping_delay_days"] < 0).sum()

0

In [52]:
# Check route status values

operations["route_status"].value_counts()

route_status
Delayed      20038
Normal       10264
Disrupted      998
Name: count, dtype: int64

In [101]:
# Save the cleaned dataset

operations.to_csv("cleaned_weekly_route_operations.csv", index=False)
country.to_csv("cleaned_country_metadata.csv", index=False)

trade.to_csv("cleaned_trade_routes.csv", index=False)

timeline.to_csv("cleaned_weekly_timeline.csv", index=False)

commodity.to_csv("cleaned_commodity_market.csv", index=False)

geo.to_csv("cleaned_geopolitical_events.csv", index=False)

## Conclusion

- No missing values found.
- No duplicate rows found.
- Date column converted to datetime.
- Composite primary key (`date`, `route_id`) is valid.
- Trade volume values are valid.
- Freight cost values are valid.
- Fuel cost values are valid.
- Carbon emission values are valid.
- Container availability, port congestion, commodity price, weather disruption, and geopolitical risk values are valid.
- Shipping delay values are valid.
- Route status values are valid.

### Result

The `weekly_route_operations.csv` dataset is clean and ready for analysis.

# Data Cleaning Summary

## Objectives Achieved

- Loaded and inspected all six datasets.
- Verified data types for every table.
- Checked for missing values.
- Checked for duplicate rows.
- Validated primary keys and the composite primary key.
- Applied business rule validations.
- Converted date columns to datetime where required.
- Identified and handled mixed date formats.
- Verified data consistency across all tables.

## Result

All six datasets have been successfully cleaned and validated. The data is consistent, complete, and ready for exploratory data analysis (EDA).